name: automated build veejay
on: [push]
jobs:
  build-veejay:
    runs-on: ubuntu-26.04
    env:
      PREFIX: /usr/local/veejay
    steps:
      - uses: actions/checkout@v6
      - name: update packages
        run: sudo apt update && sudo apt upgrade -y
      - name: install dependencies
        run: sudo ./install-dependencies.sh
        working-directory: ./veejay-current
      - name: build binary packages
        run: ./build-binary-packages.sh all
        env:
          PKG_CONFIG_PATH: "${{ env.PREFIX }}/lib/pkgconfig"
          PACKAGE_ARGS: --prefix="${{ env.PREFIX }}" --with-ndi=no
        working-directory: ./veejay-current
      - name: check if is installed veejay
        run: ls -l .
        working-directory: ./veejay-current
      - name: upload built veejay binaries
        run: echo TODO uploadt binaries
