name: build veejay
# TODO: when builds are triggered?
on: [push]
jobs:
  build-veejay:
    runs-on: ubuntu-26.04
    env:
      PREFIX: /usr/local/veejay
    steps:
      - uses: actions/checkout@v6
      - name: install dependencies
        run:
          scripts/print-deps.sh scripts/deps.list | xargs sudo apt install -y
      - name: build veejay
        run:
          PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig" ./run-and-install-locally.sh --prefix="$PREFIX" --with-ndi=no
        working-directory: ./veejay-current
      - name: check if is installed veejay
        run: ls -lR "$PREFIX"
      - name: TODO: upload built veejay binaries
        run: echo 'TODO: uploadt binaries'
